name: ProxyServerHider
version: 1.0
api-version: 1.13
description: A Plugin aims to add a bit of protection for hosting that doesn't give firewall support
main: top.apip.proxyserverhider.ProxyServerHider
commands:
  psh:
    description: Main Command For The Plugin